config/routes.rb
Rails.application.routes.draw do
  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root 'home#index'

  # comedian
  resources :users do
    resources :comedians
  end
  get '/comedians', to: 'comedians#show_all', as: :comedians

  # stage
  resources :users do
    resources :stages do
      member do
        post :join
      end
    end
  end
  get '/stages', to: 'stages#show_all', as: :stages

end

app/models/comedian.rb
class Comedian < ApplicationRecord
  # validation
  validates :stage_name,
            presence: true,
            length: { maximum: 50 }
  validates :comment,
            presence: true,
            length: { maximum: 200 }

  # relation
  belongs_to :user, optional: true
  belongs_to :genre
  has_one_attached :image
  has_many :joins
  has_many :stages, through: :joins
end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  before_action :authenticate_user!
  before_action :build_comedian, only: %i(new create)
  before_action :get_comedian, only: %i(show edit update destroy)

  def new
  end

  def create
    user = User.find(params[:user_id])
    comedian = user.build_comedian(comedian_params)

    if comedian.save
      redirect_to root_path, notice: '芸人登録が完了しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    if @comedian.delete
      redirect_to root_path, notice: '芸人情報を削除しました'
    else
      render :show
    end
  end

  def update
    if @comedian.update(comedian_params)
      redirect_to user_comedian_path(params[:user_id], params[:id]), notice: '芸人情報を更新しました'
    else
      render :edit
    end
  end

  def show_all
    @comedians = Comedian.all.order(created_at: :desc)

    render :all
  end

  # private
  def comedian_params
    params.require(:comedian).permit(:stage_name, :comment, :genre_id, :image)
  end

  def build_comedian
    @comedian = current_user.build_comedian
  end

  def get_comedian
    @comedian = Comedian.where(user_id: params[:user_id]).first
  end
end

app/views/comedians/all.html.erb
<% render partial: 'shared/page_title', locals: { page_title: '芸人一覧' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="mt-10 mx-auto w-[80%]">
  <h1 class="font-bold mb-5">芸人一覧(全<%= @comedians.size %>人)</h1>
  <div class="flex items-center justify-start bg-indigo-50 p-4">
    <% @comedians.each do | comedian | %>
    <div class="w-1/3 overflow-hidden rounded-xl bg-white shadow-md hover:shadow-xl">
    <% if comedian.image.attached? %>
    <%= image_tag comedian.image, class: 'h-auto w-full' %>
    <% else %>
    <%= image_tag 'user.png', class: 'h-auto w-full' %>
      <% end %>
      <div class="p-5">
        <h2 class="text-medium mb-5 text-gray-700"><%= comedian.stage_name %></h2>
        <p class="text-medium mb-5 text-gray-700"><%= comedian.comment %></p>
        <%= link_to '詳細ページ', user_comedian_path(comedian.user, comedian), class: "w-full block text-center rounded-md bg-indigo-600  py-2 text-indigo-100 hover:bg-indigo-500 hover:shadow-md duration-75" %>
      </div>
    </div>
    <% end %>
  </div>
  </div>

app/views/comedians/edit.html.erb
<% render partial: 'shared/page_title', locals: { page_title: '芸人情報編集' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="block p-6 rounded-lg shadow-lg bg-white w-[80%] max-w-[1200px] mx-auto">
  <%= form_with model: @comedian, url: user_comedian_path(@comedian.user, @comedian), local: true do |comedian| %>
  <% if @comedian.errors.any? %>
  <div id="error_explanation">
    <ul class="text-my-red">
      <% @comedian.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group mb-6">
    <%= comedian.label :stage_name, '芸名', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= comedian.text_field :stage_name, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none' %>
  </div>
  <div class="form-group mb-6">
    <%= comedian.label :comment, 'コメント', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= comedian.text_area :comment, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none', rows: 5 %>
  </div>
  <div class="form-group mb-6">
    <%= comedian.label :genre_id, 'ジャンル', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= comedian.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" }  %>
  </div>
  <div class="form-group mb-6">
    <%= comedian.label :image, '画像', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= comedian.file_field :image %>
  </div>
  <%= comedian.submit '更新する', class: 'w-full
      px-6
      py-2.5
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      cursor-pointer' %>
  <% end %>
  <%= link_to '戻る', root_path %>
</div>

app/views/comedians/new.html.erb
<% render partial: 'shared/page_title', locals: { page_title: '芸人登録' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="block p-6 rounded-lg shadow-lg bg-white w-[80%] max-w-[1200px] mx-auto">
  <%= form_with model: @comedian, url: user_comedians_path(current_user), local: true do |new_comedian| %>
  <% if @comedian.errors.any? %>
  <div id="error_explanation">
    <ul class="text-my-red">
      <% @comedian.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group mb-6">
    <%= new_comedian.label :stage_name, '芸名', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_comedian.text_field :stage_name, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none' %>
  </div>
  <div class="form-group mb-6">
    <%= new_comedian.label :comment, 'コメント', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_comedian.text_area :comment, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none', rows: 5 %>
  </div>
  <div class="form-group mb-6">
    <%= new_comedian.label :genre_id, 'ジャンル', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_comedian.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" }  %>
  </div>
  <div class="form-group mb-6">
    <%= new_comedian.label :image, '画像', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_comedian.file_field :image %>
  </div>
  <%= new_comedian.submit '登録する', class: 'w-full
      px-6
      py-2.5
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      cursor-pointer' %>
  <% end %>
  <%= link_to '戻る', root_path %>
</div>

app/views/comedians/show.html.erb
<% render partial: 'shared/page_title', locals: { page_title: '芸人プロフィール' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<h1 class="bg-white text-center p-2">芸人プロフィール</h1>

<div class="bg-gray-300 py-10">
  <div class="w-[70%] sp:w-[90%] mx-auto bg-gray-100 py-10 px-20 sp:px-10">
    <div class="flex sp:block justify-center gap-5">
      <div class="w-[40%] sp:w-full">
        <% if @comedian.image.attached? %>
          <%= image_tag @comedian.image, class: 'w-full sp:w-[70%] sp:mx-auto h-auto object-cover' %>
        <% end %>
      </div>
      <div class="w-[60%] sp:w-full sp:text-center sp:mt-5">
        <h2 class="text-2xl"><%= @comedian.stage_name %></h2>
        <p class="mt-5"><%= @comedian.user.email %></p>
        <p class="mt-5">ジャンル</p>
        <p class="mb-5"><%= @comedian.genre.name %></p>
        <%= link_to 'ライブ作成', new_user_stage_path(@comedian.user), class: 'py-2 px-4 border border-gray-800 rounded-lg inline-block' %>
        <%= link_to '編集', edit_user_comedian_path(@comedian.user, @comedian), class: 'py-2 px-4 border border-gray-800 rounded-lg inline-block' %>
        <%= button_to '削除', user_comedian_path(@comedian.user, @comedian), class: 'py-2 px-4 border border-gray-800 rounded-lg', method: :delete, data: { confirm: '本当に削除して宜しいですか？' } %>
      </div>
    </div>
    <h3 class="bg-[#DEFFFE] text-center mt-10 text-lg">コメント</h3>
    <p class="mt-5 text-center"><%= @comedian.comment %></p>
    <h3 class="mt-10 text-center text-xl">出演予定のライブ(<%= @comedian.joins.size %>件)</h3>
    <ul class="text-center">
      <% if @comedian.joins.any? %>
      <% @comedian.joins.each do |join| %>
      <li class="mt-5"><%= link_to join.stage.title, user_stage_path(@comedian.user.id ,join.stage), class: 'hover:underline' %></li>
      <% end %>
      <% else %>
      <li class="mt-5">参加予定のライブはありません</li>
      <% end %>
    </ul>
  </div>
  <div class="mt-5 mx-auto text-center">
  <%= link_to '芸人一覧に戻る', comedians_path, class: 'hover:underline' %>
  </div>
</div>

<style>
 .button_to{
  display: inline-block;
 }
</style>