config/routes.rb
Rails.application.routes.draw do
  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root 'home#index'

  # comedian
  resources :users do
    resources :comedians
  end
  get '/comedians', to: 'comedians#show_all', as: :comedians

  # stage
  resources :users do
    resources :stages do
      member do
        post :join
      end
    end
  end
  get '/stages', to: 'stages#show_all', as: :stages

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def is_exists_comedian(user_id)
    res = Comedian.where(user_id: user_id)
    res.any?
  end

  def get_comedian_id(user_id)
    res = Comedian.where(user_id: user_id).first
    res.id
  end
end

app/views/home/index.html.erb
<% render partial: 'shared/page_title', locals: { page_title: 'トップ' } %>

<div class="w-full h-screen relative">
  <%= image_tag 'lp-image.jpg', class: 'w-full h-auto object-cover' %>
  <div class="absolute left-0 right-0 top-[50%] text-center">
    <% if user_signed_in? && current_user.is_comedian %>
    <% if is_exists_comedian(current_user) %>
    <% comedian_id = get_comedian_id(current_user) %>
    <%= link_to '芸人プロフィール', user_comedian_path(current_user, comedian_id), class: 'inline-block px-6 py-2.5 bg-my-yellow text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
    <% else %>
    <%= link_to '芸人登録', new_user_comedian_path(current_user), class: 'inline-block px-6 py-2.5 bg-my-yellow text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
    <% end %>
     <%= link_to 'ライブ一覧', stages_path, class: 'inline-block px-6 py-2.5 bg-my-red text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
     <%= link_to '芸人一覧', comedians_path, data: { turbo_method: :delete }, class: 'inline-block px-6 py-2.5 bg-my-yellow text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
     <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'inline-block px-6 py-2.5 bg-my-red text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
    <% else %>
    <%= link_to '利用登録', new_user_registration_path, class: 'inline-block px-6 py-2.5 bg-my-yellow text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
    <%= link_to 'ログイン', new_user_session_path, class: 'inline-block px-6 py-2.5 bg-my-red text-white font-medium text-lg leading-tight uppercase rounded shadow-md hover:opacity-75 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' %>
    <% end %>
  </div>
</div>