config/routes.rb
Rails.application.routes.draw do
  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # root
  root 'home#index'

  # comedian
  resources :users do
    resources :comedians
  end
  get '/comedians', to: 'comedians#show_all', as: :comedians

  # stage
  resources :users do
    resources :stages do
      member do
        post :join
      end
    end
  end
  get '/stages', to: 'stages#show_all', as: :stages

end

app/models/stage.rb
class Stage < ApplicationRecord
  # validation
  validates :title,
            presence: true,
            length: { maximum: 50 }
  validates :performance_date,
            presence: true
  validates_date :performance_date
  validates_time :starting_time
  validates_time :closing_time
  validates :venue,
            presence: true,
            length: { maximum: 100 }
  validates :price,
            presence: true,
            numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :comment,
            length: { maximum: 200 }

  # relation
  belongs_to :user
  has_many :joins
  has_many :comedians, through: :joins
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
    before_action :authenticate_user!
    before_action :get_user, only: %i(new create show join)
    before_action :get_comedian, only: %i(show join)

    def new
      @stage = @user.stages.build
    end

    def create
      logger.debug('▼')
      logger.debug(stage_params)
      logger.debug('▼')
      stage = @user.stages.new(stage_params)

      if stage.save
        redirect_to root_path, notice: '新しいライブ情報を登録しました'
      else
        render :new
      end
    end

    def show_all
      @stages = Stage.all.order(created_at: :desc)

      render :all
    end

    def show
      @stage = Stage.find(params[:id])
    end

    def join
      stage = Stage.find(params[:id])
      @comedian.stages << stage
      redirect_to user_comedian_path(@user, @comedian), notice: stage.title + 'に参加しました'
    end


    # private
    def stage_params
    params.require(:stage).permit(:title, :performance_date, :starting_time, :closing_time, :venue, :price, :comment)
    end

    def get_user
      @user = User.find(params[:user_id])
    end

    def get_comedian
      @comedian = Comedian.where(user_id: params[:user_id]).first
    end
end

app/helpers/stages_helper.rb
module StagesHelper
  def put_wday(day)
    wdays = %w[日 月 火 水 木 金 土 日]
    '(' + wdays[day] + ')'
  end

  def number_to_currency(price)
    "#{price.to_formatted_s(:delimited)}円"
  end

  def is_joined(comedian, stage)
    res = Join.where(comedian_id: 1).where(stage_id: 1)

    !res.any?
  end
end

app/views/stages/all.html.erb
<% render partial: 'shared/page_title', locals: { page_title: 'ライブ一覧' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="mt-10 mx-auto w-[80%]">
<h1 class="font-bold mb-5">ライブ一覧(全<%= @stages.size %>件)</h1>
<% @stages.each do |stage| %>
  <div class="block p-3 rounded-lg shadow-lg bg-white mx-auto w-full">
    <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2"><%= stage.title %></h5>
    <p class="text-gray-700 text-base mb-4">
      <%= stage.comment %>
    </p>
    <%= link_to user_stage_path(stage.user, stage), class: 'contents' do %>
    <button type="button" class=" inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">詳細を見る</button>
    <% end %>
    <p class="text-gray-700 text-base mb-4 text-right">
      <%= l stage.performance_date %>
    </p>
    <% if stage.user.id == current_user.id %>
    <p class="text-gray-700 text-base text-right">
      <span class="material-icons cursor-pointer" title="あなたはこのライブの主催者です">
        person
      </span>
    </p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/stages/new.html.erb
<% render partial: 'shared/page_title', locals: { page_title: 'ライブ登録' } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="block p-6 rounded-lg shadow-lg bg-white w-[80%] max-w-[1200px] mx-auto">
  <%= form_with model: @stage, url: user_stages_path(@user), local: true do |new_stage| %>
  <% if @stage.errors.any? %>
  <div id="error_explanation">
    <ul class="text-my-red">
      <% @stage.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group mb-6">
    <%= new_stage.label :title, 'ライブタイトル', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_stage.text_field :title, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none', placeholder: 'ライブタイトルを入力' %>
  </div>
  <div class="form-group mb-6">
    <%= new_stage.label :performance_date, 'ライブ日付', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_stage.date_field :performance_date, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none' %>
  </div>
  <div class="form-group mb-6">
    <%= label('', '時間', class: 'form-label inline-block mb-2 text-gray-700') %><br />
    <%= new_stage.time_field :starting_time, class: 'ml-5' %>
    <span class="text-3xl">~</span>
        <%= new_stage.time_field :closing_time %>
  </div>
  <div class="form-group mb-6">
    <%= new_stage.label :venue, '会場', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_stage.text_field :venue, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none', placeholder: '会場名を入力(例)中野サンプラザなど' %>
  </div>
  <div class="form-group mb-6">
    <%= new_stage.label :price, '料金', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_stage.number_field :price, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none', placeholder: '料金を入力', min: 0 %>
  </div>
  <div class="form-group mb-6">
    <%= new_stage.label :comment, 'コメント', class: 'form-label inline-block mb-2 text-gray-700' %><br />
    <%= new_stage.text_area :comment, autofocus: true, class: 'form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none', rows: 5, placeholder: 'ライブの見どころや意気込みなど' %>
  </div>
  <%= new_stage.submit '登録する', class: 'w-full
      px-6
      py-2.5
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      cursor-pointer' %>
  <% end %>
  <%= link_to '戻る', root_path %>
</div>

app/views/stages/show.html.erb
<% render partial: 'shared/page_title', locals: { page_title: @stage.title } %>

<header>
  <%= render partial: 'shared/header' %>
</header>

<div class="block p-6 rounded-lg shadow-lg bg-white w-[80%] max-w-[1200px] mx-auto">
<div class="text-center">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <tbody>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">ライブタイトル</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @stage.title %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">ライブ日付</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= l(@stage.performance_date) + put_wday(@stage.performance_date.wday) %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">時間</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= l @stage.starting_time %><span class="text-3xl" style="vertical-align: sub;">~</span><%= l @stage.closing_time %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">会場</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @stage.venue %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">料金</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= number_to_currency(@stage.price) %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">ライブ主催者</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @comedian.stage_name %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">コメント</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @stage.comment %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">関連ジャンル</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @comedian.genre.name %>
              </td>
            </tr>
            <tr class="border-b">
              <th class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">参加予定人数</th>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= @stage.joins.size %>人
              </td>
            </tr>
          </tbody>
        </table>
        <% if is_joined(@comedian, @stage) %>
        <%= button_to '参加する', join_user_stage_path(@comedian, @stage), class: 'py-2 px-4 border border-gray-800 rounded-lg', method: :post, data: { confirm: 'このライブに参加しますか？' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <%= link_to '戻る', root_path, class: 'underline' %>
</div>